### ISSUE TITLE
support Domain Object Type 

### ISSUE THREAD

**Issue by arne123** [christiansandberg/canopen#113]
I just figured out that a Domain Type Object is ignored when parsing an eds file

I Have an eds where with an domain Type Object:
[3000]
ParameterName=bunchofdata
ObjectType=0x2
DataType=0x000F
AccessType=rw

I'd like to access this object with the Block Transfer.

**Comment by christiansandberg** [comment]
I can make domain object types be parsed as variables, since at least in this example the data type is also domain (0xF).

**Comment by christiansandberg** [comment]
I haven't understood the difference between an object of object type DOMAIN and a variable with data type DOMAIN. I've committed a change in master.

**Comment by arne123** [comment]
great job, works fine!
