### ISSUE TITLE
Concurrent SDO access casuses an SdoCommunicationError

### ISSUE THREAD

**Issue by comkieffer** [christiansandberg/canopen#125]
In a multi-threaded scenario if two threads try to access SDOs at the same time then on of them will fail with an `SdoCommunicationError` after reading a response for the other SDO. 

Is it your goal to make the library thread-safe or should thread synchronization be pushed into the calling code ? If you would like the library to be thread safe I can look into a patch for this problem.

**Comment by christiansandberg** [comment]
It wouldn’t hurt to make it thread safe. If you’re up to it you are welcome to provide a patch. Perhaps a simple lock would suffice?

**Comment by christiansandberg** [comment]
I would probably add it under the upload and download methods. It won’t work when using the file API, but it will be easier to implement.

**Comment by comkieffer** [comment]
This won't be a good enough solution unfortunately. PDOs also seem to interfere with SDOs. I need to test this a bit more but won't have time for at least another week. 

A better solution might to make the SDO code more tolerant to unexpected responses. Instead of assuming that the first message to come back is the response it should wait for so milliseconds and discard any invalid messages it receives in the meantime.

**Comment by af-silva** [comment]
Improvement registered and follow up at #143 
Closing this issue.
