### ISSUE TITLE
PDO save ro objects

### ISSUE THREAD

**Issue by simhein** [christiansandberg/canopen#133]
Hello
I think the pdo save workaround starting at: https://github.com/christiansandberg/canopen/blob/d3f313e2cf4249eb7459b69040376580632a61b0/canopen/pdo/base.py#L349
shall be done for every subindex because maybe the following objects are read only also.

**Comment by acolomb** [comment]
Subindex 0 in the array is the length. So we are actually not trying to overwrite an entry, but set the number of entries to zero. That's why the workaround is to fill our mapping array to the expected length.

**Comment by ShatQQ** [comment]
Okay I got that one, but what I don't understand also is the next step in `for var in self.map:`.
In this loop you try to overwrite the values in the map_array (`self.map_array[subindex].raw = (var.index << 16 | var.subindex << 8 | var.length)`) with the created dummy values from the filled self.map. And this is also the part i meant. The Object which shall be written in this case can also be read only and the error code 0x06010002 is responded.

**Comment by acolomb** [comment]
In that block, we simply don't catch any exceptions.  If a device specifies a length of the mapping array, but then does not allow write access to the specified number of entries, that is a serious protocol violation which is currently not handled.  I don't see a clear way how that **should** be handled, so the code just throws the exception up the caller chain.

Do you have some specific expectation what should happen in case the entries cannot be written?

**Comment by christiansandberg** [comment]
I guess that the maps are not possible to be changed during runtime, but you still want to be able to change other properties. It could make sense to continue even if the maps are read-only.

**Comment by acolomb** [comment]
But then how does one get notified that the mapping could not be saved? I think an exception is the Right Thing to do in this case. Setting other stuff can always be done manually without using `save()`.

**Comment by christiansandberg** [comment]
Hmm, we could continue with the configuration so that it completes but raise the exception in the end so that the application can choose to ignore it if it is an expected error.

**Comment by acolomb** [comment]
Sounds reasonable. It's still a workaround for devices that do not actually support mapping at all, so I think the OP could just not call the save method instead. "Writing a read only object" when saving the map is a pretty concise failure description IMHO.

**Comment by christiansandberg** [comment]
You make a valid point. I realised that it was more difficult than I originally thought. You can still write the communication parameters manually so it is not a deal breaker. I'll revert my change.

**Comment by ShatQQ** [comment]
Hey thanks for the answer. Maybe it would be good to somehow distinguish between saving communication parameters and mapping parameters or both? Or maybe an option to deactivate trying to write a const/ro mapping parameter by checking the od.access_type in the map_array? Right now I chosen the way not to call the save method.

**Comment by friederschueler** [comment]
This issue is solved with #273 and subscribing only instead of saving.
