### ISSUE TITLE
unicode

### ISSUE THREAD

**Issue by Tanrikulu** [christiansandberg/canopen#137]
Hello all,

I get an unicodedecode error, when I add my eds file directory into the code:
'ascii' codec can't decode byte 0xb2 in position 47: ordinal not in range(128)

I am using python 3.5. Do you know how to fix this problem?

**Comment by christiansandberg** [comment]
The file probably contains non-ascii characters. Try to create a file pointer with the file's encoding and pass it instead of the path to to the EDS-file.

```python
fp = open('od.eds', encoding='utf8')
node = canopen.RemoteNode(x, fp)
```

**Comment by Tanrikulu** [comment]
Hi,

thank you for your feedback. Unfortunately it does not work anyway. Now, I get this error-message:

`TypeError: 'encoding' is an invalid keyword argument for this function`
