### ISSUE TITLE
Network is down

### ISSUE THREAD

**Issue by Tanrikulu** [christiansandberg/canopen#138]
Hello,

I want to run the following test-code:

```
import canopen

network = canopen.Network()
network.connect(bustype='socketcan', channel='can0')
```

I get this error-message: `can.CanError: Error receiving: [Errno 100] Network is down`
But after typing 'sudo ip link set up can0' in a shell, the test-code works. Does anyone know how to set up the can network in python?

**Comment by Tanrikulu** [comment]
ok, I have fixed that.
I just add:
```
import os
os.system('sudo ip link set up can0')
```

**Comment by big17** [comment]
import os
os.system('sudo ip link set can0 up type can bitrate 250000')
