### ISSUE TITLE
Disconnect Can bus and CAN network after each use

### ISSUE THREAD

**Issue by amostafa9** [christiansandberg/canopen#186]
Do I have to disconnect the CAN bus and CAN network after each time i use the bus/network? I notice that often times if I do not disconnect both the master and slave's can bus, I often will get errors, like an SDO communication error that says no SDO received.

To fix this, I manually reset the slave node by disabling the CAN bus and re-enabling. 
What is the cause of this error?

**Comment by christiansandberg** [comment]
It’s good practice to always disconnect something that you previously connected to or close opened files for example. Not doing this may lead to undefined and unexpected behavior.
