### ISSUE TITLE
In SDO download command not possible send binary negative value 

### ISSUE THREAD

**Issue by daddi1987** [christiansandberg/canopen#197]
Trying to use the SDO download function I can't send a binary negative value. I always answer this error:

- canopen.sdo.exceptions.SdoAbortedError: Code 0x06070012, Data type does not match, length of service parameter too high

My code works like this:
`MOTOR_LOADER.sdo.download(0x3001, 0, "b'\xff\xff\xff\xff\xff\xff\xff\x02'")`

![Capture](https://user-images.githubusercontent.com/39605171/88699333-8126c780-d107-11ea-97ef-489962f1cc8c.PNG)

**Comment by christiansandberg** [comment]
It seems you need to remove the "" around the bytes.

**Comment by daddi1987** [comment]
Sorry, the screen is referment of a test string. 
The correct string is:
`MOTOR_LOADER.sdo.download(0x3001, 0, b'\xff\xff\xff\xff\xff\xff\xff\x20')`

and error is
![Capture](https://user-images.githubusercontent.com/39605171/88765125-51fb6f00-d176-11ea-8ee5-780facd86119.PNG)

**Comment by christiansandberg** [comment]
And you're sure the variable is a 64-bit integer? What if you try to upload the current value?

**Comment by daddi1987** [comment]
sorry, the problem was with my driver set to 16 Bit. Congratulations on the excellent CanOpen library and support.
