### ISSUE TITLE
Failed to parse default value of form `integer + $NODEID'.

### ISSUE THREAD

**Issue by gmkado** [christiansandberg/canopen#198]
I'm new to CanOpen so forgive me if this issue does not make sense.  I was using this eds editor https://github.com/robincornelius/libedssharp

It stored the TPDO COB-ID default parameter as `0x180+$NODEID` instead of `$NODEID+0x180` and so didnt get parsed correctly.  Could you instead look for both conditions?

Referencing this comment:

Thanks! I checked and it is not required to support complex expressions, so we can assume it is always `$NODEID+integer`.

_Originally posted by @christiansandberg in https://github.com/christiansandberg/canopen/pull/50#issuecomment-342169496_

**Comment by christiansandberg** [comment]
That should be doable. I'll try to have a look at it next week unless you want to do PR yourself.

**Comment by gmkado** [comment]
Thanks!
