### ISSUE TITLE
Node402 => BaseNode402

### ISSUE THREAD

**Issue by hellmerf** [christiansandberg/canopen#212]
Please check...
####################################
Create a node with Node402:

import canopen
from canopen.profiles.p402 import Node402

some_node = Node402(3, 'someprofile.eds')
network = canopen.Network()
network.add_node(some_node)
####################################
on https://canopen.readthedocs.io/en/latest/profiles.html

Should be : some_node = BaseNode402(3, 'someprofile.eds') ? (worked for me...)

Thank you very much for your work !
Frank

**Comment by af-silva** [comment]
Hi @hellmerf , you absolutely right. Thanks for pointing this, i corrected the documentation.
