### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Oyssster** [christiansandberg/canopen#220]
When I install the canopen by: `pip install canopen`.
I encounter the error:
ERROR: Could not find a version that satisfies the requirement windows-curses (from python-can>=3.0.0->canopen) (from versions: none)
ERROR: No matching distribution found for windows-curses (from python-can>=3.0.0->canopen)
How can I solve the problem?
THANKS.

**Comment by christiansandberg** [comment]
It's an issue with python-can: https://github.com/hardbyte/python-can/issues/932
