### ISSUE TITLE
Help wanted: How to simply receive a message

### ISSUE THREAD

**Issue by Neokimx** [christiansandberg/canopen#232]
Hello folks,

maybe someone can help me with my nooby question.
I'm trying to communicate with a motor via CANBus.

I'm able to create a network, to add a node and to utilize the SDO options of the canopen library.
I can control the state machine and the motor with that.

But I didn't manage to communicate with raw CAN messages on the bus.

For example:
`my_network = canopen.Network()`
`my_network.connect(bustype='ixxat', channel=0, bitrate=50000)`
`my_network.add_node(17)`
`my_network.send_message(0x611, data, remote=False)`

The above code works. I can see the outgoing message with the help of CAN Analizer software. I can also see that the motor responds with a CAN message in this software.

Now my question: How can I receive the message within my code?
I tried to use:
`my_network.subscribe(0x591, callback)`

But that doesn't work. 
The code just runs through and doesn't trigger the callback, allthouh I can see the incoming message with CAN-ID 591 in my analyzer software.

Do I have to use the Listeners or the notify option?
Maybe someone can give me some code example since I'm not that familiar with programming?!

In general, I would like to know how to read or receive messages on the bus.

I would appreciate some help.
Thanks in advance,
Daniel

**Comment by Neokimx** [comment]
Ok, I found my mistake. I used:

`my_network.subscribe(can_id,callback())`

and he executed the callback every time.
Wasn't familiar with a function call vs a function handle

Now with:
`my_network.subscribe(can_id,callback)`

`def callback(*args, **kwargs):`
`can_id = args`
`timestamp = kwargs`

it's working and I receive the message with specific CAN-ID.

However I still don't know why I should need Listeners or Notify.

**Comment by Neokimx** [comment]
Ok, my fault was not to wait for the response.
With a little sleep or a while True loop it works like intended

**Comment by christiansandberg** [comment]
Good to hear!

**Comment by rakamafo** [comment]
> 
> 
> Ok, my fault was not to wait for the response.
> With a little sleep or a while True loop it works like intended

@Neokimx : Can you share a snippet of code in the callback on how to implement this. or how to use the listeners or notify or subscriber functions in the class. Im not too familiar with programming. Thanks in advance !

**Comment by Neokimx** [comment]
I didn't manage to implement listeners or the the notify option. Unfortunately I'm quite new to programming and therefore didn't know what to do either. If someone else can post a code snippet I would appreciate this aswell ;D

But I was able to use the subscribe method to read messages on the bus.
Below a rudimentary code snippet. Here, I want to read the serial number of the connected motor.

```
serial_number = []

# Create network (I used an IXXAT transceiver)
my_network = canopen.Network()
my_network.connect(bustype='ixxat', channel=0, bitrate=500000)

# Add node to network (in my case the motor has the node ID 0x11 (17))
my_network.add_node(0x11)

# Create data list (in this case I want to read the serial number of the motor)
data = [0x40, 0x18, 0x10, 0x04, 0x00, 0x00, 0x00, 0x00]

# Subscribe to CAN-ID where you expect the answer (in this case 0x591 = 0x580 + 0x11, for SDO TX + Node-ID)
my_network.subscribe(0x591, callback)  # callback function to trigger when message received, see definition below

# Send the message with CAN-ID and data for serial number request (0x600 + 0x11, for SDO RX + Node-ID)
my_network.send_message(0x611, data, remote=False)

# Wait for the motor to respond
while serial_number == []:
  time.sleep(0.1)

print(serial_number)

# Callback function definition
def callback(can_id, data, timestamp):
  print(data)
  unpacked_data = struct.unpack("<4cl", data)  # use of struct.unpack method to decode the bytearray
  serial_number = unpacked_data[4]
```

I didnt test this but thats the way I implemented it in my code and it works there.
I would like to hear from you if you can manage to do it or when you can use notifier or listeners. Would like to use them but don't know how to. Subscribing to a message feels like a inconvenient workaround.

**Comment by Neokimx** [comment]
Update: I tried the code myself. Made some fixes, but the below version works for me:

```
import canopen
import time


# Callback function definition
def my_callback(can_id, can_data, timestamp):
    print(can_data)


# Create network (I used an IXXAT transceiver)
my_network = canopen.Network()
my_network.connect(bustype='ixxat', channel=0, bitrate=500000)

# Add node to network (in my case the motor has the node ID 0x11 (17))
my_network.add_node(0x11)

# Create data list (in this case I want to read the serial number of the motor)
data = [0x40, 0x18, 0x10, 0x04, 0x00, 0x00, 0x00, 0x00]

# Subscribe to CAN-ID where you expect the answer (in this case 0x591 = 0x580 + 0x11, for SDO TX + Node-ID)
my_network.subscribe(0x591, my_callback)  # callback function to trigger when message received, see definition below

# Send the message with CAN-ID and data for serial number request (0x600 + 0x11, for SDO RX + Node-ID)
my_network.send_message(0x611, data, remote=False)

time.sleep(1)
```

**Comment by 3sigma** [comment]
Hello,

To use listeners, you need to do this:

`listener = canopen.network.MessageListener(network)

def on_message(msg):
    # Very simple message processing...
    print(msg)
listener.on_message_received = on_message

network.notifier.add_listener(listener)`
