### ISSUE TITLE
virtual device - no sdo response recieved

### ISSUE THREAD

**Issue by HayfaNc** [christiansandberg/canopen#236]
I'm really new to canopen and I'm still learning.. I have to create a virtual canopen slave with python to communicate with an existing master.

When running my script I keep getting this error "no sdo response recieved"  and I didn't know how to fix it..
I think it may be a problem with the sdo server as mentioned here #20

Is it possible to create a virtual sdo server? does it really fix the problem?
do I need to use another library to send response to master requests? 
otherwise, does anyone have an idea on how to fix that problem?

**Comment by friederschueler** [comment]
Probably your master was no answering the SDO commands. What do you mean with "virtual sdo server".
Closing this as it is really old issue. Feel free to open a new one with more example code and read the documentation, it is really good.
