### ISSUE TITLE
Not able to remap PDO with more variable than eds file

### ISSUE THREAD

**Issue by prunith** [christiansandberg/canopen#243]
Hi,
There is an issue when wy try to remap pdo.
My EDS file contains only one variable for RPDO 1and when i try to add additional variable with rpdo[1].add_variable() when i try send rpdo[1].save() i got message "Subindex 2 was not found".

I dig into your code and found that when eds fill is red pdo are saved to a Record "map_array". Save function try to override this Record but but if number of variable is greater than specified in EDS it fail because number of index in "map_array" is lower than required.

**Comment by friederschueler** [comment]
Problem is unclear. Without code and corresponding EDS-File we can't help either. Closing this now, feel free to open a new issue with a better description and example.
