### ISSUE TITLE
Min and max limits are limited to integer type

### ISSUE THREAD

**Issue by p139933** [christiansandberg/canopen#266]
First of all, thank all of you for giving us this master peace of software!

I notice small issue in min / max limits. Both them are forced to integer type, but in eds it is possible to define limits for real number too. I know that reals are not so common, but there are some devices using them. It would be nice to have limit support for real numbers too.

**Comment by sveinse** [comment]
This is implemented in the current canopen library if I'm not mistaking, so I believe this issue can be closed.
