### ISSUE TITLE
[Q] how can I enable or disable logs?

### ISSUE THREAD

**Issue by ymkim92** [christiansandberg/canopen#27]
Hi,

I like this code but I am not good at Python. 
I want to enable all logger output or some of modules.
Can you advise me how to do that?

Regards,
Young

**Comment by christiansandberg** [comment]
This can be done through the [logging](https://docs.python.org/3/library/logging.html) module.

```python
import logging
logging.basicConfig(level=logging.DEBUG)
import canopen
```

Or setting level for a specific module:
```python
logging.getLogger('canopen.sdo').setLevel(logging.DEBUG)
```

**Comment by christiansandberg** [comment]
If you need more help you can continue writing in this thread.

**Comment by ymkim92** [comment]
It works very well. Thank you very much.
