### ISSUE TITLE
OD values from .dcf not loaded

### ISSUE THREAD

**Issue by martinlucan** [christiansandberg/canopen#274]
Since I need a version compatible with Python 2, I use a fork of the version which is automatically installed via “pip install canopen” (ver. 1.2.1), with Cyclic Synchronous modes additionally implemented in p402.py file. Unfortunately, I have noticed that the configuration saved in the standard .dcf file is NOT uploaded at motor startup. Therefore I have to always use manufacturers' software to change some parameters. Both, .dcf and .eds files are supported in documentation. Do you know what might cause this problem of not uploading a configuration? Is .eds format preferred over .dcf?

**Comment by martinlucan** [comment]
Thank you @acolomb for the answer. We would prefer to upload parameters from .dcf to the device at startup. Could you please provide me with some example code on how to do so?

**Comment by acolomb** [comment]
Can you upload the DCF file here? I don't know how it will work exactly, but I'm sure a solution is possible when reusing some code parts from this library.

**Comment by martinlucan** [comment]
Sure, I guess, it doesn't matter on a .dcf file, but here is a sample file:

[dcf.zip](https://github.com/christiansandberg/canopen/files/7496949/dcf.zip)

**Comment by martinlucan** [comment]
I simply made use of` import_eds` function from `objectdictionary.eds`, although parameters from .dcf file are not loaded anyways.   @acolomb do you know what might be the issue? Do I have to use any other function? Thank you.

**Comment by acolomb** [comment]
As I said, I don't think the code is designed to read the actual object *values* from DCF files.  Just the object dictionary *structure*.  You may be able to extend that.  Sorry I don't have time right now to look into it deeper.

**Comment by acolomb** [comment]
Fixed by #427.  Sorry for not really understanding the purpose of the DCF file usage here when I first looked at the issue.
