### ISSUE TITLE
What is the best way to get synced OD value from multiple nodes at once?

### ISSUE THREAD

**Issue by mzahana** [christiansandberg/canopen#299]
Hi,

I have 4 motor controllers that use CANopen for communication. I was able to use the `canopen` library to control them.

I start network sync as follows
```python
self._network.sync.start(sync_dt)
```
The current speed is mapped t `tpdo[1]`, for each node, as follows
```python
try:
   # Read PDO configuration from node
   node.tpdo.read()
   
   # Re-map TxPDO_id
   node.tpdo[pdo_id].clear()
   #node.tpdo[pdo_id].add_variable('StatusWord')
   node.tpdo[pdo_id].add_variable(var2beMapped[0])   # in 0.1 rpm
   node.tpdo[pdo_id].add_variable(var2beMapped[1]) # in encoder counts
   #node.tpdo[pdo_id].add_variable('Mode of operation display')
   node.tpdo[pdo_id].trans_type = 1
   node.tpdo[pdo_id].event_timer = 0
   node.tpdo[pdo_id].enabled = True
   # Save new PDO configuration to node
   node.tpdo.save() # node must be in PRE-OPERATIONAL NMT state
except Exception as e:
   logging.error("Could not configure TPDO {} for node {}".format(pdo_id, node_id))
```
I try to get each motor's speed as follows
```python
def getVelocity(self, node_id):
      """
      Gets velocity value of a particular node

      Parameters
      --
      @param node_id Node ID [int]

      Returns
      --
      @return vel Velocity in m/s. Raises an exception on error
      """
      try:
         node = self._network[node_id]
         node.tpdo[1].wait_for_reception()
         speed = node.tpdo[1]['Current speed'].phys
         return speed * self._rpm_scaler
      except Exception as e:
         logging.error("Could not get velocity for node {}. Error: {}".format(node_id, e))
```

When I try to get the current speed of each motor using `getVelocity(node_id=i)`, I notice that there is a fixed delay between each call of `getVelocity` which is equal to the `sync_dt` in `self._network.sync.start(sync_dt)`. Is there a way to get all motor's speeds (or any other OD value) at the same time, without having to waita fixed delay between each request?

@christiansandberg any hints?

Thanks

**Comment by christiansandberg** [comment]
Yes, use the callback mechanism instead. There is an example in the README.

https://canopen.readthedocs.io/en/latest/pdo.html#canopen.pdo.Map.add_callback
