### ISSUE TITLE
basic steps of python-canopen for two linux nodes

### ISSUE THREAD

**Issue by ytuemrah** [christiansandberg/canopen#311]
I am a bit confused about CANopen and python implementation,
I want to build a basic system with two nodes, one of them is master and the other one is slave, one of them is server and the other one is client, one of them is producer and the other one is consumer.. 
I want to setup with two Ubuntu PCs,
Do I need to run two python programs simultaneously with a while True loops? (I think as network socket communication)
Will both side have the same program with different eds files? (in the eds file there are parameters as follows ; SimpleBootUpMaster=0 SimpleBootUpSlave=1, will we determine the node status via .eds file)
Also I have two Pcan-USB devices with can0 socket interfaces, I can send CANopen messages with other applications, I have tested.
 When I tried to run following code in the one side of Ubuntu PC the other side just has "candump" program, 
```
import canopen
import os
network = canopen.Network()
EDS_PATH = os.path.join(os.path.dirname(__file__), 'e35.eds')
node = canopen.RemoteNode(35,EDS_PATH)
network.add_node(node)
network.connect(bustype='socketcan', channel='can0', bitrate=125000)
device_name = node.sdo['Device name'].raw
```
I received the following error:
```
    t(int(eds.get("DeviceInfo", eprop), 0))
ValueError: invalid literal for int() with base 0: '001'
```
I have overcame it by changing "VendorNumber" parameter from 001 to 1.
Then have received following error:
```
    raise SdoCommunicationError("No SDO response received")
canopen.sdo.exceptions.SdoCommunicationError: No SDO response received
```
When the device_name is assigned like that " = node.sdo['Device name']" , without .raw, the device_name becomes an address without error, but i think it is not right.
Finally, I want to connect two linux nodes via Pcan-USB with python-canopen, and want to see nmt, sdo messages on the candump, what is the basic steps?
I know it takes long but I get stuck,
Thank you for your time and consideration
Best Regards

**Comment by af-silva** [comment]
Hi @ytuemrah, the error:
``` 
t(int(eds.get("DeviceInfo", eprop), 0))
ValueError: invalid literal for int() with base 0: '001'
```
Was identifier on #313 and is already fixed. The VendorNumber was invalid. 

Regarding your other question. 
Canopen is mainly to be used as a Master node, but I think you can try to implement a demo using both the 'RemoteNode' master side and 'LocalNode' slave side. See this [Link](https://canopen.readthedocs.io/en/latest/network.html) .

**Comment by ratna225** [comment]
Hello Christian,
I developed two EDS file with one as master and other as slave. I configured tpdo's of master as slave rpdo's and viceversa. I configured two nodes one as remote node(slave.eds) and other as local node (master.eds). I checked for the heartbeat by using node1.nmt.start_heartbeat(10), local_node1.nmt.wait_for_heartbeat(10) commands and there is no error. But when I am trying to read tpdo's of remote node, I am receiving the below error. Please help me in fixing the issue. My idea is the tpdo's(master) should transfer the data and the data should be received by rpdo's(slave).

File "C:\Users\ratat\PycharmProjects\tests\canopenhardwaretest.py", line 222, in func1
local_node1.tpdo.read()
File "C:\Python39\lib\site-packages\canopen\pdo\base.py", line 56, in read
pdo_map.read()
File "C:\Python39\lib\site-packages\canopen\pdo\base.py", line 318, in read
cob_id = self.com_record[1].raw
File "C:\Python39\lib\site-packages\canopen\variable.py", line 75, in raw
value = self.od.decode_raw(self.data)
File "C:\Python39\lib\site-packages\canopen\variable.py", line 37, in data
return self.get_data()
File "C:\Python39\lib\site-packages\canopen\sdo\base.py", line 128, in get_data
return self.sdo_node.upload(self.od.index, self.od.subindex)
File "C:\Python39\lib\site-packages\canopen\sdo\client.py", line 117, in upload
fp = self.open(index, subindex, buffering=0)
File "C:\Python39\lib\site-packages\canopen\sdo\client.py", line 205, in open
raw_stream = ReadableStream(self, index, subindex)
File "C:\Python39\lib\site-packages\canopen\sdo\client.py", line 251, in init
response = sdo_client.request_response(request)
File "C:\Python39\lib\site-packages\canopen\sdo\client.py", line 85, in request_response
return self.read_response()
File "C:\Python39\lib\site-packages\canopen\sdo\client.py", line 73, in read_response
raise SdoAbortedError(abort_code)
canopen.sdo.exceptions.SdoAbortedError: Code 0x06020000, Object does not exist
