### ISSUE TITLE
Some "Transfer aborted by client with message" printed unexpectedly

### ISSUE THREAD

**Issue by prunith** [christiansandberg/canopen#315]
Hi since latest version i see many message "Transfer aborted by client with xxxx" printed in terminal. Especially when SDO request timeout.
I see in code that those messages are sent to the logger but i don't understand why it is printed to the terminal.

**Comment by edcloudcycle** [comment]
I think because it is the driver reporting to STDERR not the python library.

**Comment by friederschueler** [comment]
Is the question why you are seeing theese messages or how to get rid of them?

The default python logger will forward all messages to stderr, as edcloudcycle said. Closing this, as it is old and no real question or bug?
