### ISSUE TITLE
How connect USB-CAN Adapter

### ISSUE THREAD

**Issue by sasha1396** [christiansandberg/canopen#331]
Hello there! Very nice code, but I still haven't been able to try it. Can you please tell me how can I use canopen with USBCAN adapter? My adapter is defined as a single USB device:

![image](https://user-images.githubusercontent.com/37298586/193218162-a44c4b12-f8e8-40a5-90e0-2eabfea80c99.png)

It looks like this:

![photo_2022-09-19_19-57-43](https://user-images.githubusercontent.com/37298586/193218022-6955d6cf-b839-4cb1-9765-4b60b32aec62.jpg)
![photo_2022-09-19_19-58-02](https://user-images.githubusercontent.com/37298586/193218045-43c21522-8e49-41c9-8bc8-86052e5c2381.jpg)
![photo_2022-09-19_19-58-04](https://user-images.githubusercontent.com/37298586/193218058-58c2acab-695e-4d31-b124-cc3e6ea9fcf9.jpg)

And I still have not figured out which interface to use for it and how. I would appreciate any help and directions to the right place.

**Comment by christiansandberg** [comment]
You should ask in the python-can project instead. I haven't heard of it so it may not be supported. But you should be able to write a backend for it if you can find a description of the API.
