### ISSUE TITLE
how to use a modified version of python-can

### ISSUE THREAD

**Issue by mgiaco** [christiansandberg/canopen#35]
Hey Christian,

Really great project! I do have a question: Is there a way to install python-can so that I can modify it and canpoen use that modified version.

many thanks

**Comment by christiansandberg** [comment]
Sure, you can install python-can in [develop mode](https://packaging.python.org/distributing/#working-in-development-mode).

```
git clone https://github.com/hardbyte/python-can.git
cd python-can
pip install -e .
```

**Comment by mgiaco** [comment]
cool many thanks
