### ISSUE TITLE
Confusing Variable class names used for different purposes

### ISSUE THREAD

**Issue by sveinse** [christiansandberg/canopen#363]
After spending quite many hours in the codebase, there is one thing I find really confusing and time consuming: Some classes are named the same thing, but with different functions. Applies to `Variable` and partly to `Array` and `Record`. 

```py
    variable.Variable
    pdo.base.Variable  # Inherited from variable.Variable
    sdo.base.Variable  # Inherited from variable.Variable
    objectdictionary.Variable
```

I understand the functions for all of these. and I get it if the intention was to make a duck-type like class, but they're really not all compatible. It does not help that type checkers and linters often displays the base name of the class, not the full path. If the type checker report an error where it expects `Variable`, a small investigation is required to figure out which of these classes is the one that should be used.

I would like to suggest to change the class names into unique names as follows:

```py
    class Variable:  # in variable.py
    class PdoVariable(Variable):
    class SdoVariable(Variable):
    class ODVariable:
```
Likewise for `Array` into `class SdoArray` and `class ODArray`, and `Record` into `class SdoRecord` and `class ODRecord`. I don't intend any changes to the methods and the class inheritance. If we need to keep the old names intact for compatibility, we can do so as aliases in the respective files. I can spin up a PR if there's interest for this.

**Comment by acolomb** [comment]
I wouldn't mind as long as the aliases are still available to not break other code.
