### ISSUE TITLE
Update number of unused bytes in last SDO segment

### ISSUE THREAD

**Issue by jongo728** [christiansandberg/canopen#4]
When trying to perform a SDO segmented download to one of our devices the transfer fails when the data size is not a multiple of 7.

This is due to the client indicating the size of the complete transfer and the server verifying the total number of bytes received after receiving the last segment. When the last segment is received the server interprets n=0b000 as the segment containing 7 bytes of data and thus will fail the transfer due to a mismatch between received and expected.

**Comment by christiansandberg** [comment]
Thank you for the report. Should be a simple fix.
