### ISSUE TITLE
reset communication in nmt state

### ISSUE THREAD

**Issue by ymkim92** [christiansandberg/canopen#40]
Hi Christian,

I hardly use 'RESET COMMUNICATION' state.
But I think if it is 'RESET**-**COMMUNICATION', it is better at my CLI.
'PRE-OPERATIONAL' has '-'. Why not for 'RESET COMMUNICATION'.

Regards,
Young

**Comment by christiansandberg** [comment]
I took names exactly as they are named in the DS-301 standard. PRE-OPERATIONAL is one word while RESET COMMUNICATION is two words. You don't have to use those if you don't want to. You can use the node.nmt.send_command() method to send raw NMT commands.

**Comment by christiansandberg** [comment]
I'll go ahead and close this for now.
