### ISSUE TITLE
eds file for curtis controller

### ISSUE THREAD

**Issue by intertwistlet** [christiansandberg/canopen#411]
Maybe a silly question and not that related. But how can i get the eds file for a curtis controller, like curtis F2A?
I have went through 1314 pc software, but no where i can dump such files.
Thanks for any possible help.

**Comment by acolomb** [comment]
You need the WinVCL tool (not quite sure about the name) which allows writing own programs for the integrated controller.  And probably in addition the firmware file for your controller, from Curtis.  Then when you compile a VCL program (can be an empty dummy), it outputs the matching EDS file.

On the other hand, contacting Curtis support to get the standard EDS for your firmware directly is maybe the easier approach.

**Comment by intertwistlet** [comment]
Thanks
