### ISSUE TITLE
Missing datatype 0x16 -> UNSIGNED24

### ISSUE THREAD

**Issue by prunith** [christiansandberg/canopen#466]
Hi,
Could you implement USIGNED24 bits datatype ? Hex code is 0x16.

Thierry

**Comment by sveinse** [comment]
I'm not familiar with UNSIGNED12 in canopen. Datatype 0x16 is according to CiA 301 UNSIGNED24. Where is UNSIGNED12 used?

**Comment by prunith** [comment]
Hi @sveinse you are right i made a mistake UNSIGNED24 is missing UNSIGNED12 does not exist so far.

**Comment by prunith** [comment]
I dig into code to see how it can be implemented, unfortunatly canopen use struct library that not support 24bit data. Perhaps with this work arround it could work unpack('<l', b'\x57\x15\x00' + b'\x00')[0] # unsigned littleendian

**Comment by prunith** [comment]
I see also that pull request already submited to correct that #267 unfortunately it was mixed with other change and not implemented.

**Comment by prunith** [comment]
Tanks @sveinse @acolomb i m just late from one week , i have not noticed new release. Anyway i confirm it is fixed with 2.3.0.
Unfortunatly i have noticed some issue with latest python_can 4.4.0 library. I ll open a new ticket if needed.

**Comment by acolomb** [comment]
What issues specifically? The canopen 2.3.0 release should work around an incompatible change in python-can 4.4.0 already.  And for the next python-can release, the incompatibility is fixed again on their end already, just not released.
