### ISSUE TITLE
pytest fails on master due to TestEDS.test_export_eds_to_file

### ISSUE THREAD

**Issue by sveinse** [christiansandberg/canopen#501]
I'm running Windows and the tests fails:

```
TestEDS.test_export_eds_to_file
TestEDS.test_export_eds_to_file_unknown_extension
```

Both fails with:

```
test\test_eds.py:235:    # The second is test fails on line 245
canopen\objectdictionary\__init__.py:58: PermissionError
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sveinse\\AppData\\Local\\Temp\\tmp00_selbk.eds'
```

I'm not sure why this specific test doesn't work in Windows while the others works fine.

**Comment by erlend-aasland** [comment]
Sorry, this my fault; I used `tempfile.NamedTemporaryFile`, which returns a writable and opened file. `canopen` tries to open it again, which works fine on Linux and macOS, but fails on Windows.
