### ISSUE TITLE
"unpack requires a bytes object of length 1" message in a background thread

### ISSUE THREAD

**Issue by saouinet** [christiansandberg/canopen#55]
Hi, 
thank you for your job. I just started some trials and can't get out of this "unpack requires a bytes object of length 1".
can you help?
I'm on windows 10+ anaconda (python 3.5) and using an IXXAT

**Comment by christiansandberg** [comment]
It’s probably your heartbeat messages that are not 1 byte exactly. Though it’s probably not good that the thread crashes due to this so I’ll do something about that.

**Comment by saouinet** [comment]
Super !!! 
Thanks a lot
