### ISSUE TITLE
New PyPi release

### ISSUE THREAD

**Issue by Muschasgrazias** [christiansandberg/canopen#62]
Hey,

Could you release a new PyPi version, as the last version is 0.5.1 which was released in October.

Best regards

**Comment by christiansandberg** [comment]
I’ll try to do that very soon.

**Comment by christiansandberg** [comment]
I've published [v0.6.0rc1](https://pypi.python.org/pypi/canopen/0.6.0rc1). If I don't get any bug reports I'll release it next week.

**Comment by christiansandberg** [comment]
0.6.0 is now live!
