### ISSUE TITLE
Provide optional counter parameter in SYNC messages

### ISSUE THREAD

**Issue by randycoulman** [christiansandberg/canopen#63]
Thanks so much for this library! It's exactly what we needed for the project I'm working on!

According to the spec, SYNC messages can have an optional `counter` parameter:

> The optional parameter counter shall be incremented by 1 with every transmission. The maximum value shall be the current value as defined in the synchronous counter overflow value (see sub-clause 7.5.2.22). In case the maximum value is reached the counter shall be set to 1 with the next transmission. The initial value of the counter after the NMT service boot-up shall be 1. The value of the counter shall be reset to 1 if the CANopen device transits from the NMT state stopped into the NMT state pre-operational or into the NMT state operational.

When writing tests against a device, it would be handy to be able to provide this count value.

A good first step would be to be able to provide it in the `transmit()` call: `network.sync.transmit(42)`.

Full support would involve maintaining a count value, resetting it when necessary, and wrapping according to the overflow value, then sending it with each SYNC after using `network.sync.start(0.1)`.

For now, I've implemented a workaround in my project with `network.send_message(0x80, bytes([count]))`, and that works fine, but wondering if it would be better to have it built into the library.

**Comment by christiansandberg** [comment]
We could definitely modify the `transmit()` method to include a counter. Periodic transmission is a little harder now because I recently changed the implementation to use the hardware or kernel periodic transmission when possible for improved timing. This also means that we can't modify the content on each message.
