### ISSUE TITLE
Using a custom backend

### ISSUE THREAD

**Issue by HpLightcorner** [christiansandberg/canopen#93]
Hey!

With some of the latest commits i got into troubles when using a custom backend as described in the documentation - I think the library now strongly depends on python-can’s CyclicSendTask. At least the way described in the documentation (Using a custom backend) does not work as the CyclicSendTasks are missing.

I would suggest to remove the custom backend (at least from documentation) and point out that it's quite easy to extend python-can (which has a software-based CyclicSendTask fallback) using entry-points.

Hopefully I did not duplicate any ongoing issues.

Regards!

**Comment by christiansandberg** [comment]
Yes I agree. The cyclic functionality wasn’t there before so it was slightly easier then.

**Comment by christiansandberg** [comment]
Same for the ability to use plugins in python-can so I should update the docs to describe how to write a plugin instead.
