### ISSUE TITLE
Issue on Windows --> solved

### ISSUE THREAD

**Issue by pycan** [christiansandberg/canopen#98]
Hi,

Recently, I come cross CANopen. I started using it on linux and it is just worked fine. However, the same script does not show the same behavior on Windows. It always could not go further that changing the state from preoperational to operational. When I try receiving my pdo's, I got an error message that complains on the SDO that is not sent/received. Could you please tell me what do I need to go on with my design. Note that PCAN-USB and/or PCAN-PCI Express is used (https://www.peak-system.com/PCAN-USB.199.0.html?&L=1) (https://www.peak-system.com/PCAN-PCI-Express.206.0.html?&L=1).  
Moreover, I use socketcan drivers on Linux, whereas use peak can drivers on windows.

Windows Error:
===========

Traceback (most recent call last):
  File "D:/workspace/CANopenTest/CANopen.py", line 191, in <module>
    master.write_sdo(1, index, 2, 32/8, 1024.0)
  File "D:/workspace/CANopenTest/CANopen.py", line 152, in write_sdo
    raise Exception('ERROR: unable to write sdo: {reason}'.format(reason=e))
Exception: ERROR: unable to write sdo: No SDO response received
Exception in thread can.notifier for bus "PCAN_PCIBUS1" (most likely raised during interpreter shutdown):

Any idea what went wrong?

Many thanks in advace

**Comment by christiansandberg** [comment]
Have you specified the correct bitrate in your connect() call?

**Comment by pycan** [comment]
Hi Christian,

Thanks for your reply.

Now a bit further. The below error speared after collecting the first coming pdo's 

ERROR message:
===========
error(10038, 'An operation was attempt on something that is not a socket')

Many thanks in advance

**Comment by pycan** [comment]
Thanks Christian,

It works now. The node idea was wrong
