### ISSUE TITLE
SDO Error Message

### ISSUE THREAD

**Issue by natemay17** [christiansandberg/canopen#99]
Hi,

First thanks for developing this module! It will work perfectly with what I am working on right now! I am still getting a little used to the software and I keep getting a "No SDO response received" error message and I am not 100% sure what is going on, but I am probably doing something wrong. I am using a Kvaser bus with a leaf light V2.

My EDS file is here: https://drive.google.com/open?id=1-XbPUKq6BUiPghrR5hEO76K93uCKRPdG

import canopen

network = canopen.Network()
network.connect(bustype='kvaser', channel=0, bitrate=500000, can_filters=None)

node = network.add_node (1,'C:/Users/nathaniel.may/Allied Motion Technologies Inc/Shearer, Jeff - Labview Library/Common Files/Allied Motion/AM_Drive.eds')

for obj in node.object_dictionary.values():
    print('0x%X: %s' % (obj.index, obj.name))
    if isinstance(obj, canopen.objectdictionary.Record):
        for subobj in obj.values():
            print('  %d: %s' % (subobj.subindex, subobj.name))

for node_id in network:
    print(network[node_id])
  
V_Bus = node.object_dictionary[0x2025]
print (V_Bus)

V_Bus = node.sdo[0x2025]

print("The device Vbus is 0x%X" % V_Bus.raw)

**Comment by christiansandberg** [comment]
Difficult to say. Are you sure that the node ID is 1 and that the bitrate is 500 kbit? Have you used the kvaser interface with some other program so you know that the channel works? Have you logged the CAN traffic?
